import React from 'react';

export const PdfFooter = ({ generatedBy }: { generatedBy: string }) => {
  const styles: Record<string, React.CSSProperties> = {
    footerContainer: {
      marginTop: 'auto',
      paddingTop: '8px',
      borderTop: '1px solid #e5e7eb',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      fontFamily: '"Inter", sans-serif',
      fontSize: '9px', // Smaller font for footer
      color: '#9ca3af',
    },
    left: {
      display: 'flex',
      flexDirection: 'column',
      gap: '2px',
    },
    right: {
      textAlign: 'right',
    },
  };

  const currentDate = new Date().toLocaleString('en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return (
    <div style={styles.footerContainer}>
      <div style={styles.left}>
        <span>Generated By: {generatedBy}</span>
        <span>Date: {currentDate}</span>
      </div>
      <div style={styles.right}>
        <span>@warqad</span>
      </div>
    </div>
  );
};
